apiVersion: v1
kind: Secret
metadata:
  name: upmdb-app-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.upmdb.auth.username | quote }}
  password: {{ .Values.upmdb.auth.password | quote }}
