{{- if not .Values.accounts }}
{{- fail "values.accounts must contain at least one SFTP account" }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}-config
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
data:
  sftp-users: |
    {{- range .Values.accounts }}
    {{ .username }}:{{ .password }}:{{ .uid }}:{{ .gid }}
    {{- end }}
