{{- if .Values.hostKeys.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp.hostKeysSecretName" . }}
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
type: Opaque
data:
  ssh_host_ed25519_key: {{ .Files.Get "files/host-key/ssh_host_ed25519_key" | b64enc | quote }}
  ssh_host_rsa_key: {{ .Files.Get "files/host-key/ssh_host_rsa_key" | b64enc | quote }}
{{- end }}
