apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: upmdb-cluster
  namespace: {{ .Release.Namespace }}
spec:
  instances: 3
  imageName: {{ .Values.upmdb.imageName | quote }}
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      timezone: "Asia/Seoul"
      log_timezone: "Asia/Seoul"
  affinity:
    nodeSelector:
      node-group.ntels.io/type: upm-app
    tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      nodeAffinityPolicy: Honor
      nodeTaintsPolicy: Honor
      labelSelector:
        matchLabels:
          cnpg.io/cluster: upmdb-cluster
          cnpg.io/podRole: instance
  storage:
    size: {{ .Values.upmdb.storage.size | quote }}
    storageClass: {{ .Values.upmdb.storage.storageClass | quote }}
  bootstrap:
    initdb:
      database: {{ .Values.upmdb.database | quote }}
      owner: {{ .Values.upmdb.auth.username | quote }}
      secret:
        name: upmdb-app-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology;
  {{- if or .Values.upmalert.enabled .Values.upmems.enabled }}
  managed:
    roles:
      {{- if .Values.upmalert.enabled }}
      - name: {{ .Values.upmalert.auth.username | quote }}
        ensure: present
        login: true
        passwordSecret:
          name: upmalert-app-secret
      {{- end }}
      {{- if .Values.upmems.enabled }}
      - name: {{ .Values.upmems.auth.username | quote }}
        ensure: present
        login: true
        passwordSecret:
          name: upmems-app-secret
      {{- end }}
  {{- end }}
