{{- if .Values.upmalert.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: upmalert-app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.upmalert.auth.username | quote }}
  password: {{ .Values.upmalert.auth.password | quote }}
{{- end }}
