{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "alerta.fullname" .) .Values.secret.name }}
  labels:
    {{- include "alerta.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.stringData }}
  {{- range $key, $val := .Values.secret.stringData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}
{{- end }}
