apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: upm-ems
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    inhibit_rules:
      # kube-prometheus-stack 기본 inhibit
      - equal: [namespace, alertname]
        source_matchers: [severity = critical]
        target_matchers: [severity =~ "warning|info"]
      - equal: [namespace, alertname]
        source_matchers: [severity = warning]
        target_matchers: [severity = info]
      - equal: [namespace]
        source_matchers: [alertname = InfoInhibitor]
        target_matchers: [severity = info]
      - target_matchers: [alertname = InfoInhibitor]

    receivers:
      - name: "null"
      - name: alerta
        webhook_configs:
          - url: "http://alerta.upm-ems.svc.cluster.local:8080/api/webhooks/prometheus"
            send_resolved: true

    route:
      group_by: [namespace]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "null"
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: "null"
        - matchers:
            - environment = "MetricAlert"
          receiver: alerta
          group_by: [service, instance]
          group_wait: 10s
          group_interval: 1m
          repeat_interval: 5m

    templates:
      - /etc/alertmanager/config/*.tmpl
